config/routes.rb
Rails.application.routes.draw do
  resources :projects

  root 'pages#index'

  get 'pages/profile'

  get 'repositories', to: 'repositories#index'

  get 'auth/:provider/callback', to: 'sessions#create'

  delete 'sign_out', to: 'sessions#destroy'

  resources :repositories

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/repository.rb
class Repository < ActiveRecord::Base
  belongs_to :user
  validates_uniqueness_of :full_name

  def self.save_repo_info(repos, id)
    repos.collect do |repo|
      create(
        owner: repo["owner"]["login"],
        name: repo["name"],
        description: repo["description"],
        full_name: repo["full_name"],
        repo_url: repo["html_url"],
        user_id: id
      )
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :repositories

  def self.sign_in_from_omniauth(auth)
    find_by(provider: auth["provider"], uid: auth["uid"]) || create_user_from_omniauth(auth)
  end

  def self.create_user_from_omniauth(auth)
    create(
      provider: auth["provider"],
      uid: auth["uid"],
      name: auth["info"]["name"],
      email: auth["info"]["email"],
      username: auth["info"]["nickname"]
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_user!
    if current_user.nil?
      redirect_to root_url
    end
  end

  helper_method :current_user, :authenticate_user!
end

app/controllers/pages_controller.rb
require "pry"
class PagesController < ApplicationController
  before_action :set_auth
  before_action :authenticate_user!, :current_user, only: [:profile]

  def index
    if current_user
      redirect_to :controller => "repositories", :action => "index"
    end
  end

  def profile
  end

  private

  def set_auth
    @auth = session[:omniauth] if session[:omniauth]
  end

  # def repo_params
  #   params.require(:repository).permit(:name, :description, :full_name, :username, :email)
  # end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :repo, :description)
    end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_auth
  # , only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :current_user, only: [:index]

  # GET /repositories
  # GET /repositories.json
  def index
    github = Github.new
    @repos_info = github.repos.list user: current_user.username
    @repositories = Repository.save_repo_info(@repos_info, current_user.id)
  end

  # GET /repositories/1
  # GET /repositories/1.json
  #   def show
  #   end
  #
  #   # GET /repositories/new
  #   def new
  #     @repository = Repository.new
  #   end
  #
  #   # GET /repositories/1/edit
  #   def edit
  #   end
  #
  #   # POST /repositories
  #   # POST /repositories.json
  #   def create
  #     @repository = Repository.new(repository_params)
  #
  #     respond_to do |format|
  #       if @repository.save
  #         format.html { redirect_to @repository, notice: 'Repository was successfully created.' }
  #         format.json { render :show, status: :created, location: @repository }
  #       else
  #         format.html { render :new }
  #         format.json { render json: @repository.errors, status: :unprocessable_entity }
  #       end
  #     end
  #   end
  #
  #   # PATCH/PUT /repositories/1
  #   # PATCH/PUT /repositories/1.json
  #   def update
  #     respond_to do |format|
  #       if @repository.update(repository_params)
  #         format.html { redirect_to @repository, notice: 'Repository was successfully updated.' }
  #         format.json { render :show, status: :ok, location: @repository }
  #       else
  #         format.html { render :edit }
  #         format.json { render json: @repository.errors, status: :unprocessable_entity }
  #       end
  #     end
  #   end
  #
  #   # DELETE /repositories/1
  #   # DELETE /repositories/1.json
  #   def destroy
  #     @repository.destroy
  #     respond_to do |format|
  #       format.html { redirect_to repositories_url, notice: 'Repository was successfully destroyed.' }
  #       format.json { head :no_content }
  #     end
  #   end
  #
  private
  #     # Use callbacks to share common setup or constraints between actions.
  # def set_repository
  #   @repository = Repository.find(params[:id])
  # end
  def set_auth
    @auth = session[:omniauth] if session[:omniauth]
  end
  #
  #     # Never trust parameters from the scary internet, only allow the white list through.
  #     def repository_params
  #       params[:repository]
  #     end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    session[:omniauth] = auth.except("extra")
    user = User.sign_in_from_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:omniauth] = nil
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_footer.html.erb
<footer class="mdl-mega-footer">
  <div class="mdl-mega-footer__middle-section">

    <div class="mdl-mega-footer__drop-down-section">
      <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
      <h1 class="mdl-mega-footer__heading">Features</h1>
      <ul class="mdl-mega-footer__link-list">
        <li><a href="#">About</a></li>
        <li><a href="#">Terms</a></li>
        <li><a href="#">Partners</a></li>
        <li><a href="#">Updates</a></li>
      </ul>
    </div>

    <div class="mdl-mega-footer__drop-down-section">
      <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
      <h1 class="mdl-mega-footer__heading">Details</h1>
      <ul class="mdl-mega-footer__link-list">
        <li><a href="#">Specs</a></li>
        <li><a href="#">Tools</a></li>
        <li><a href="#">Resources</a></li>
      </ul>
    </div>

    <div class="mdl-mega-footer__drop-down-section">
      <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
      <h1 class="mdl-mega-footer__heading">Technology</h1>
      <ul class="mdl-mega-footer__link-list">
        <li><a href="#">How it works</a></li>
        <li><a href="#">Patterns</a></li>
        <li><a href="#">Usage</a></li>
        <li><a href="#">Products</a></li>
        <li><a href="#">Contracts</a></li>
      </ul>
    </div>

    <div class="mdl-mega-footer__drop-down-section">
      <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
      <h1 class="mdl-mega-footer__heading">FAQ</h1>
      <ul class="mdl-mega-footer__link-list">
        <li><a href="#">Questions</a></li>
        <li><a href="#">Answers</a></li>
        <li><a href="#">Contact us</a></li>
      </ul>
    </div>

  </div>

  <div class="mdl-mega-footer__bottom-section">
    <div class="mdl-logo">Title</div>
    <ul class="mdl-mega-footer__link-list">
      <li><a href="#">Help</a></li>
      <li><a href="#">Privacy & Terms</a></li>
    </ul>
  </div>

</footer>

app/views/layouts/_header.html.erb
<!-- Always shows a header, even in smaller screens. -->
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <span class="mdl-layout-title">Title</span>
      <!-- Add spacer, to align navigation to the right -->
      <div class="mdl-layout-spacer"></div>
      <!-- Navigation. We hide it in small screens. -->
      <nav class="mdl-navigation mdl-layout--large-screen-only">
        <%= link_to "Sign in", "auth/github", class: "mdl-navigation__link remove-links-decor" %>
      </nav>
    </div>
  </header>
  <div class="mdl-layout__drawer">
    <span class="mdl-layout-title">Title</span>
    <nav class="mdl-navigation">
      <a class="mdl-navigation__link" href="">Link</a>
      <a class="mdl-navigation__link" href="">Link</a>
      <a class="mdl-navigation__link" href="">Link</a>
      <a class="mdl-navigation__link" href="">Link</a>
    </nav>
  </div>
  <main class="mdl-layout__content">
    <div class="page-content">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </main>
</div>




<!-- Uses a transparent header that draws on top of the layout's background -->
<!-- <style> __>
/*.demo-layout-transparent {
  background: rgb(33,150,243) center / cover;
}*/
/*.demo-layout-transparent .mdl-layout__header,
.demo-layout-transparent .mdl-layout__drawer-button {*/
   /*This background is dark, so we set text to white. Use 87% black instead if
     your background is light.*/
  /*color: white;
}
</style>

<!-- <div class="demo-layout-transparent mdl-layout mdl-js-layout">
  <header class="mdl-layout__header mdl-layout__header--transparent">
    <div class="mdl-layout__header-row"> -->
      <!-- Title -->
      <!-- <span class="mdl-layout-title">Title</span> -->
      <!-- Add spacer, to align navigation to the right -->
      <!-- <div class="mdl-layout-spacer"></div> -->
      <!-- Navigation -->
      <!-- <nav class="mdl-navigation">
        <a class="mdl-navigation__link" href="">Link</a>
        <a class="mdl-navigation__link" href="">Link</a>
        <a class="mdl-navigation__link" href="">Link</a>
        <a class="mdl-navigation__link" href="">Link</a>
      </nav>
    </div>
  </header>
  <div class="mdl-layout__drawer">
    <span class="mdl-layout-title">Title</span>
    <nav class="mdl-navigation">
      <a class="mdl-navigation__link" href="">Link</a>
      <a class="mdl-navigation__link" href="">Link</a>
      <a class="mdl-navigation__link" href="">Link</a>
      <a class="mdl-navigation__link" href="">Link</a>
    </nav>
  </div>
  <main class="mdl-layout__content">
    <%= yield %>
  <%= render "layouts/footer" %>
  </main>
</div> -->

app/views/layouts/_signed_in_header.html.erb
<!-- Always shows a header, even in smaller screens. -->
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <span class="mdl-layout-title">
        <%= link_to "Geet", root_url, class: "remove-links-decor", style: "color:white;" %>
      </span>
      <!-- Add spacer, to align navigation to the right -->
      <div class="mdl-layout-spacer"></div>
      <!-- Navigation. We hide it in small screens. -->
      <nav class="mdl-navigation mdl-layout--large-screen-only"></nav>

      <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="user-img-menu">
        <%= link_to "Profile", pages_profile_path, class: "mdl-menu__item" %>
        <%= link_to "Sign out", "sign_out", method: :delete, class: "mdl-menu__item" %>
      </ul>
    </div>
  </header>
  <div class="mdl-layout__drawer">
    <span class="mdl-layout-title move-img">
      <i><%= link_to image_tag(@auth["info"]["image"], width: "150", heigth: "150", class: "img-circle"), pages_profile_path %></i>
    </span>
    <strong align="center" style="margin-right:10px;text-decoration:underline">
      <%= link_to current_user.username, pages_profile_path %>
    </strong>
    <nav class="mdl-navigation">
      <%= link_to raw('<i class="fa fa-user fa-2x"></i>') + " Profile", pages_profile_path, class: "mdl-navigation__link remove-links-decor" %>
      <%= link_to raw('<i class="fa fa-archive fa-2x" style="margin-left:-3px"></i>') + "Repositories", repositories_path, class: "mdl-navigation__link remove-links-decor" %>
      <%= link_to raw('<i class="fa fa-power-off fa-2x"></i>') + "Log Out", sign_out_path, class: "mdl-navigation__link remove-links-decor", method: :delete %>
    </nav>
  </div>
  <main class="mdl-layout__content">
    <div class="page-content" id="center-page-content">
      <div class="mdl-grid">
        <div class="mdl-cell mdl-cell--11-col">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render "layouts/footer" %>
  </main>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeetSocial</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= analytics_init if Rails.env.production? %>
    <link href="https://storage.googleapis.com/code.getmdl.io/1.0.5/material.blue_grey-red.min.css" rel="stylesheet">
    <script src="https://storage.googleapis.com/code.getmdl.io/1.0.5/material.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  </head>
  <body>
    <% if current_user %>
      <%= render "layouts/signed_in_header" %>
    <% else %>
      <%= render "layouts/header" %>
    <% end %>
    <!-- <%= yield %> -->
  </body>
</html>

app/views/pages/index.html.erb
<div class="home-background"></div>

app/views/pages/profile.html.erb
<h1>Pages#profile</h1>
<p>Find me in app/views/pages/profile.html.erb</p>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :repo %><br>
    <%= f.text_field :repo %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Repo</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.repo %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Repo:</strong>
  <%= @project.repo %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/repositories/_form.html.erb
<%= form_for(@repository) do |f| %>
  <% if @repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
      <% @repository.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repositories/edit.html.erb
<h1>Editing Repository</h1>

<%= render 'form' %>

<%= link_to 'Show', @repository %> |
<%= link_to 'Back', repositories_path %>

app/views/repositories/index.html.erb
<h1>Repositories</h1>
<div class="mdl-grid">
  <% @repos_info.sort{|a,b| b["created_at"] <=> a["created_at"]}.each do |el| %>
  <% repo_url = el["html_url"] %>
  <div class="mdl-cell mdl-cell--4-col">
    <div class="square-card mdl-card mdl-shadow--2dp">
      <div class="mdl-card__title mdl-card--expand">
        <h2 class="mdl-card__title-text"><%= el["name"] %></h2>
      </div>
      <div class="mdl-card__supporting-text">
        <%= el["description"] %><br>
      </div>

      <div class="mdl-card__actions mdl-card--border">
        <%= link_to "Visit Repository", repo_url, class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect remove-links-decor", target: "_blank" %><br>
        <div align="right">
          <span class="material-icons mdl-badge" data-badge="<%= el['forks_count'] %>" id="forks">call_split</span>
          <div class="mdl-tooltip" for="forks">Forks</div>
          <span class="material-icons mdl-badge" data-badge="<%= el['open_issues_count'] %>" id="issues">error</span>
          <div class="mdl-tooltip" for="issues">Issues</div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/repositories/new.html.erb
<h1>New Repository</h1>

<%= render 'form' %>

<%= link_to 'Back', repositories_path %>

app/views/repositories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_repository_path(@repository) %> |
<%= link_to 'Back', repositories_path %>